# Generated by Django 4.1.7 on 2023-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core_app', '0002_quizanswers_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
