# Generated by Django 4.1.7 on 2023-03-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core_app', '0003_alter_quizmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='question',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
