# Generated by Django 4.1.7 on 2023-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core_app', '0004_quizquestions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswers',
            name='answer',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
