# Generated by Django 4.1.7 on 2023-03-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core_app', '0009_alter_quizmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='description',
            field=models.CharField(default=None, max_length=500, verbose_name='Краткое описание квиза'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
