# Generated by Django 4.1.7 on 2023-03-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core_app', '0010_quizmodel_description_alter_quizmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='description',
            field=models.CharField(default=None, max_length=120, verbose_name='Краткое описание квиза'),
        ),
    ]
