# Generated by Django 4.1.7 on 2023-04-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core_app', '0011_alter_quizmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswers',
            old_name='question',
            new_name='question_id',
        ),
    ]
